### PR TITLE
Swift 4

### LINKED ISSUE #1: Demo not work
Not clickable!

### PR DESCRIPTION
**Pull request by fespinoza**
i've converted the project to swift 4

this also closes #1 

As I explained in https://github.com/ProjectDent/LinkLabel/pull/2/commits/c5f1c0b64c523fcf79ddb81eafd15e56bc7b3ec7 I slightly changed the behavior of the pod

### CODE REVIEW

**Comment by fespinoza** [comment]
any comment @ProjectDent ?

i need your input regarding the todos :)

**Review by oliviertouron-playster — APPROVED** [review]

**Comment by oliviertouron-playster** [comment]
TouchGestureRecognizer is not correct for Swift 4

**Comment by fespinoza** [comment]
hi @oliviertouron-playster sorry for taking so long to come back. But what's the issue with `TouchGestureRecognizer` and swift 4 that you mention?. Regarding syntax i changed to use inferred type context

**Comment by fespinoza** [comment]
ping @ProjectDent @oliviertouron-playster

**Comment by PabloDomine** [comment]
Thanks @fespinoza ! 
@ProjectDent @oliviertouron-playster why isn't this merged yet? 🤔

**Pull request closed without merging**
